checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, src/Exceptions]
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: ./vendor/bin/phpunit --coverage-clover=api-client-coverage-file
                coverage:
                    file: api-client-coverage-file
                    format: clover